/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sqlin' at '7/17/16 11:53 PM' with Gradle 2.14
 *
 * @author sqlin, @date 7/17/16 11:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
